# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Dessert.destroy_all
Recipe.destroy_all
Review.destroy_all


brownies_bars = Dessert.create(name: "Brownies & Bars", dessert_image: "https://www.gimmesomeoven.com/wp-content/uploads/2013/07/Peanut-Butter-Fudge-Brownies-1.jpg")
cookies = Dessert.create(name: "Cookies", dessert_image: "http://images.media-allrecipes.com/userphotos/560x315/1107530.jpg")
cupcakes = Dessert.create(name: "Cupcakes", dessert_image: "https://www.browneyedbaker.com/wp-content/uploads/2010/11/red-velvet-cupcakes-32-600.jpg")
cakes = Dessert.create(name: "Cakes", dessert_image: "http://img1.southernliving.timeinc.net/sites/default/files/styles/story_card_two_thirds/public/image/2016/04/main/strawberry-dream-cake-2428901_0.jpg?itok=zbA9x4WX")
muffins = Dessert.create(name: "Muffin", dessert_image: "https://res.cloudinary.com/paleoleap/image/upload/f_auto,q_90/v1467159756/comp/bravoforpaleo_paleo-blueberry-muffins.jpg")
pies_tarts = Dessert.create(name: "Pies & Tarts", dessert_image: "http://www.willcookforsmiles.com/wp-content/uploads/2013/11/Apple-Pie-Custard-Tart-6-from-willcookforsmiles.com-tart-custard-applepie-650x429.jpg")

whisk = User.create!(username: "Whisk", email: "admin@google.com", password: "admin123")
sonny = User.create!(username: "Sonny", email: "sonny@google.com", password: "sonnykbp")
danielle = User.create!(username: "Danielle", email: "danielle@google.com", password: "123456")
jenny = User.create!(username: "Jenny", email: "jenny@google.com", password: "123456")
matt = User.create!(username: "Matt", email: "matt@google.com", password: "123456")
susan = User.create!(username: "Susan", email: "susan@google.com", password: "123456")


brown_butter_cookies = Recipe.create!(name: "Brown Butter Cookies", description: "Using butter (NOT margarine) is essential for the success of this rich, but highly addictive cookie! You may need as little as 3 cups confectioners' sugar for the icing; just stop adding it when you've reached the desired consistency.", ingredients: ["2 cups butter", "2 cups brown sugar", "2 eggs", "2 teaspoons vanilla extract", "1 teaspoon baking soda", "1/2 teaspoon baking powder", "1/2 teaspoon salt"], direction: "Preheat oven to 350 degrees F (175 degrees C). Heat butter over medium heat for 5 minutes or so, until it turns nut brown in color. The foaming and bubbling is part of the browning process, but watch it carefully so that you don't burn the butter. Remove from heat, and cool slightly. Reserve 1/2 cup of the butter for the frosting.
Pour remaining browned butter into a large mixing bowl. Beat browned butter with brown sugar until the butter is no longer hot. Mix in eggs, 2 teaspoons vanilla, baking soda, baking powder, and salt. Beat thoroughly. Mix in flour and chopped pecans. Drop tablespoons of dough onto ungreased baking sheets. Bake for 10 minutes in the preheated oven, or until light brown around the edges. Cool. In a medium bowl, mix the reserved 1/2 cup browned butter with 2 teaspoons vanilla, confectioners' sugar, and hot water. Beat until smooth, and use to frost cooled cookies.", preptime: 30, cooktime: 10, recipe_image: "http://images.media-allrecipes.com/userphotos/560x315/744345.jpg", dessert: cookies, user: whisk)

lemon_strawberry_crumb_bars = Recipe.create!(name: "Lemon Strawberry Crumb Bars", description: "There’s sweet, zesty, and tangy + crumby, soft, and juicy. These bars are strawberry lemonade in square form. A 9×13 pan of pure sunshine. There might be a snowstorm a-brewin’ but inside our kitchen? So long, winter.", ingredients: ["3 cups (375g) all-purpose flour","1 teaspoon baking powder", "1/2 teaspoon salt", "1 cup (230g) butter, very cold and cubed", "1 cup (200g) packed light or dark brown sugar", "1 large egg + 1 large egg yolk1", "1 teaspoon pure vanilla extract", "4 cups (650g) chopped strawberries2", "1/3 cup (67g) granulated sugar", "Zest from 1 lemon", "1 and 1/2 Tablespoons cornstarch"], direction: "Preheat the oven to 350°F (177°C). Line a 9x13 inch pan pan with parchment paper, leaving an overhang on the sides to lift the finished bars out of the pan as a whole. This makes cutting easier.
Whisk the flour, baking powder, and salt together. Add the butter and cut in with a pastry cutter or pulse in a food processor until pea-sized crumbs form. See photo above for a visual. Whisk the brown sugar, egg, egg yolk, and vanilla together. Pour into the flour/butter mixture and mix it all together by hand. I find using a spoon or rubber spatula to take much longer. Your hands are quicker and more effective! Press 2/3 of this mixture into the bottom of the prepared pan. Make sure it is very tight and compact. Mix the strawberries, granulated sugar, lemon zest, and cornstarch together until combined. Spoon evenly over crust. Crumble the remaining butter/flour mixture on top and gently press down so it's snug on the strawberry layer. Bake for 42-50 minutes or until the top is lightly browned and the strawberry filling is bubbling on the sides. Remove from the oven and place the pan on a wire rack. Allow to cool completely. I stick mine in the refrigerator to speed up the cooling process.
Whisk the glaze ingredients together and drizzle on top (or you can drizzle on individual squares). Lift the cooled bars out using the overhang on the sides. Cut into squares.", preptime: 30, cooktime: 90, recipe_image: "http://sallysbakingaddiction.com/wp-content/uploads/2015/04/Raspberry-Crumble-Bars-are-so-simple-to-make-and-one-of-those-desserts-everyone-loves-350x350.jpg", dessert: brownies_bars, user: sonny)

funfetti_cupcakes = Recipe.create!(name: "Funfetti Cupcakes", description: "There’s a unicorn craze happening right now. Everything colorful, rainbow, sparkly, and exploding with happiness is labeled “unicorn.” Have you tried the new Starbucks unicorn frappe? I’m weird and don’t like drinking blue or purple colored concoctions. I don’t know why! I’ve always been like that! No blue raspberry kool aid, no purple slushies, nada. Even if those flavors are natural.", ingredients: ["1 and 3/4 cups (200g) cake flour1","3/4 teaspoon baking powder", "1/4 teaspoon baking soda", "1/4 teaspoon salt", "1/2 cup (115g) unsalted butter, softened to room temperature", "1 cup (200g) granulated sugar", "3 large egg whites, at room temperature", "2 teaspoons pure vanilla extract", "1/2 teaspoon butter extract", "Seeds scraped from 1/2 of a vanilla bean", "1/2 cup (120g) full-fat sour cream at room temperature", "1/2 cup (120ml) whole milk at room temperature","1/2 cup rainbow sprinkles"], direction: "Preheat the oven to 350°F (177°C). Line a 12-cup muffin pan with cupcake liners. Line a second pan with 2 liners - this recipe makes about 14 cupcakes. Set aside. Make the cupcakes: Whisk the cake flour, baking powder, baking soda, and salt together. Set aside. Using a handheld or stand mixer fitted with a paddle attachment, beat the butter on high speed until smooth and creamy - about 1 minute. Add the sugar and beat on high speed for 2 minutes until creamed together. Scrape down the sides and up the bottom of the bowl with a rubber spatula as needed. Add the egg whites, vanilla + butter extracts, and vanilla bean. Beat on medium-high speed until combined, then beat in the sour cream. Scrape down the sides and up the bottom of the bowl as needed. With the mixer on low speed, add the dry ingredients until just incorporated. With the mixer still running on low, slowly pour in the milk until combined. Do not overmix. You may need to whisk it all by hand to make sure there are no lumps at the bottom of the bowl. The batter will be slightly thick. Fold in the sprinkles-- careful! Do not overmix as this could cause them to bleed color. Pour/spoon the batter into the liners - fill only 2/3 full to avoid spilling over the sides. Bake for 19-22 minutes, or until a toothpick inserted in the center comes out clean. For around 30 mini cupcakes, bake for about 11-13 minutes, same oven temperature. Allow the cupcakes to cool completely before frosting. Make the frosting: With a handheld or stand mixer fitted with a paddle attachment, beat the butter on medium speed until creamy - about 2 minutes. Add 4 and 1/2 cups confectioners' sugar, the heavy cream, and vanilla extract with the mixer running on low. Increase to high speed and beat for 3 full minutes, then beat in the food coloring. Add up to 1/2 cup more confectioners' sugar if frosting is too thin or another Tablespoon of cream if frosting is too thick. Add a pinch of salt if frosting is too sweet.",
preptime: 45, cooktime: 80, recipe_image: "http://sallysbakingaddiction.com/wp-content/uploads/2012/12/Funfetti-Cupcakes-from-scratch.jpg", dessert: cupcakes, user: jenny)

apple_crumb_pie = Recipe.create!(name: "Apple Crumb Pie", description: "You can add walnuts and raisins to this apple crumb pie to make it even dreamier!", ingredients: ["1 (9 inch) pie shell", "6 cups thinly sliced apples", "1 tablespoon lemon juice (optional)", "3/4 cup white sugar", "2 tablespoons all-purpose flour", "1/2 teaspoon ground cinnamon", "1/8 teaspoon ground nutmeg", "1/2 cup raisins (optional)", "1/2 cup chopped walnuts (optional)", "1/2 cup all-purpose", "1/2 cup packed brown","sugar 3 tablespoons butter"], direction: "Preheat oven to 375 degrees F (190 degrees C).
Place sliced apples in a large bowl. Sprinkle with lemon juice if desired. In a small bowl, mix together white sugar, 2 tablespoons flour, cinnamon, and nutmeg. Sprinkle mixture over apples. Toss until apples are evenly coated. Stir in raisins and walnuts if desired. Spoon mixture into pastry shell.
In a small bowl mix together 1/2 cup flour and brown sugar. Cut in butter or margarine until mixture is crumbly. Sprinkle mixture over apple filling. Cover top loosely with aluminum foil.
Bake in preheated oven for 25 minutes. Remove foil and bake an additional 25 to 30 minutes, until top is golden brown. Cool on a wire rack.", preptime: 30, cooktime: 60, recipe_image: "http://sallysbakingaddiction.com/wp-content/uploads/2015/07/Apple-Crumble-Pie-heavy-on-the-crumble-topping-Recipe-on-sallysbakingaddiction.com-7.jpg", dessert: pies_tarts, user: danielle)


jalapeno_cornbread_muffins = Recipe.create!(name: "Jalapeño Cornbread Muffins", description: "Chopped jalapeño adds the perfect amount of kick to my favorite cornbread muffin recipe, pairing wonderfully with the subtle sweetness of honey and brown sugar.", ingredients: ["1 cup (120g) cornmeal", "1 cup (125g) all-purpose flour", "1 teaspoon baking powder", "1/2 teaspoon baking soda", "1/8 teaspoon salt", "1/2 cup (115g) unsalted butter, melted and slightly cooled", "2 Tablespoons (30ml) canola or vegetable oil (or melted coconut oil)", "1/3 cup (67g) packed light brown sugar", "2 Tablespoons (30ml) honey", "1 large Eggland's Best egg, at room temperature", "1 cup (240ml) buttermilk, at room temperature", "1-3 chopped jalapeño peppers"], direction: "Preheat oven to 425°F (218°C). Line a 12-count muffin pan with liners or spray with nonstick spray. This recipe makes about 14 muffins, so there will be a 2nd batch. Set pan aside.
Whisk together the cornmeal, flour, baking powder, baking soda, and salt in a large bowl. Set aside. In a medium bowl, whisk the cooled melted butter, oil, brown sugar, and honey together until completely smooth and thick. There should be no brown sugar lumps. Then, whisk in the egg until combined. Finally, whisk in the buttermilk. Pour the wet ingredients into the dry ingredients and whisk until combined. Fold in the peppers. Avoid overmixing.
Spoon batter into muffin liners, filling all the way to the top. Bake for 5 minutes 425°F (218°C) then, keeping the muffins in the oven, reduce heat to 350°F (177°C)4 and continue baking for another 16-17 minutes. The total time these muffins should be in the oven is around 21-23 minutes. You'll want them baked until the center is cooked through. Use a toothpick to test.
Remove muffins from the oven and allow to cool in the pan for 5-10 minutes before enjoying.", preptime: 15, cooktime: 65, recipe_image: "http://media.tumblr.com/tumblr_m3knhwzmdR1qhhgsz.jpg", dessert: muffins, user: matt)

redvelvet_roll_cake = Recipe.create!(name: "Red Velvet Roll Cake", description: "Like most jelly roll type cakes, this is a sponge cake. But with a delicious red velvet flavor! There’s cocoa and vanilla, a little brown sugar, with a slight tang from buttermilk. It’s a light and airy cake.", ingredients: ["1 cup minus 1 Tablespoon all-purpose flour", "3 Tablespoons (15g) unsweetened natural cocoa powder", "1 teaspoon baking powder", "1/2 teaspoon salt", "4 large eggs, room temperature", "1/2 cup (100g) granulated sugar", "1/4 cup (50g) packed light brown sugar", "2 Tablespoons (30ml) canola or vegetable oil", "2 Tablespoons (30ml) buttermilk", "1 teaspoon white vinegar", "1 Tablespoon liquid red food coloring", "2 teaspoons pure vanilla extract", "6 ounces (170g) block cream cheese", "1/4 cup (1/2 stick; 60g) unsalted butter", "1 and 3/4 cups (210g) confectioners sugar"],
direction: "Preheat oven to 350°F (177°C). Spray a 10x15 inch baking pan with nonstick spray or grease with butter, so the parchment paper sticks. Then line it with parchment paper so the cake seamlessly releases in step 5. Spray or grease the parchment paper too. We want an extremely nonstick surface for this cake roll.
Sift the flour, cocoa powder, baking powder, and salt together. (Make sure they're sifted well!) Set aside.
Using a hand mixer or a stand mixer fitted with whisk attachment, beat the eggs for 5 minutes on high speed. They will be light and very fluffy. On medium speed, beat in the granulated sugar, brown sugar, oil, buttermilk, vinegar, food coloring, and vanilla until combined. Stop the mixer, pour in the sifted dry ingredients, then beat on low until the batter is completely combined. It will be a ruby red color.
Spread batter evenly into prepared pan. Give the pan a shake to make sure the batter is level and reaches the corners. Bake for 17 minutes or until the cake springs back when you poke it with a finger.
Meanwhile, lay a thin kitchen towel flat on the counter. Sprinkle with 1 cup of confectioners' sugar. Once the cake comes out of the oven, immediately invert it onto the towel. Peel off the parchment paper then, starting with the narrow end, begin rolling the cake up with the towel. Do this slowly and gently. The cake will be warm as it just came out of the oven.
Allow the cake to cool completely rolled up in the towel. I stick mine in the refrigerator for about 2 hours to speed it up.
Remove the cake roll from the refrigerator and allow to sit on the counter for a few minutes to warm up as you prepare the frosting.", preptime: 25, cooktime: 180, recipe_image: "http://www.thefatherstable.com/wp-content/uploads/2014/03/Red-Velvet-Cake-Roll-with-Cream-Cheese-Filling.jpg", dessert: cakes, user: susan)


magic_bars = Recipe.create!(name: "Magic Bars", description: "This bar cookie is an old fashioned favorite. Chocolate chips, nuts and coconut are set in a caramelized layer on top of a graham cracker crust.", ingredients: ["1/2 cup butter or margarine, melted", "1 1/2 cups graham cracker crumbs", "1 (14 ounce) can Sweetened Condensed Milk", "2 cups semisweet chocolate chips", "1 1/3 cups flaked coconut", "1 cup chopped nuts"],
direction: "Heat oven to 350 degrees F (325 degrees for glass dish). Coat 13x9-inch baking pan with no-stick cooking spray.
Combine graham cracker crumbs and butter. Press into bottom of prepared pan. Pour sweetened condensed milk evenly over crumb mixture. Layer evenly with chocolate chips, coconut and nuts. Press down firmly with a fork.
Bake 25 minutes or until lightly browned. Cool. Cut into bars or diamonds. Store covered at room temperature.", preptime: 15, cooktime: 30, recipe_image: "http://blog.fatfreevegan.com/images/magic-cookie2.jpg", dessert: brownies_bars, user: sonny)


first_review = Review.create!(body: "Awesome recipe!", recipe: brown_butter_cookies, user: sonny)
second_review = Review.create!(body: "I love how moist it is. Absolutely delicious!", recipe: lemon_strawberry_crumb_bars, user: danielle)
third_review = Review.create!(body: "A little too sweet for me so I decreased the sugar and added more salt.", recipe: funfetti_cupcakes, user: jenny)
fourth_review = Review.create!(body: "Will try this for my newphew's birthday party this Saturday :)", recipe: apple_crumb_pie, user: jenny)
fifth_review = Review.create!(body: "First try and it turned out great! Thanks for sharing!!!", recipe: funfetti_cupcakes, user: matt)
sixth_review = Review.create!(body: "Didn't come out as perfect as I thought but will try again.", recipe: jalapeno_cornbread_muffins, user: susan)
seventh_review = Review.create!(body: "Can I substitue butter for olive/vegetable oil?", recipe: brown_butter_cookies, user: susan)
eight_review = Review.create!(body: "Made it for my wife for diner last night. We ate the whole thing lol", recipe: redvelvet_roll_cake, user: matt)
ninth_review = Review.create!(body: "Thanks for the great instructions! Love all your recipes ;)", recipe: jalapeno_cornbread_muffins, user: sonny)
tenth_review = Review.create!(body: "Everyone loves this, it's addictive. Some hints, when doing the butter/graham crust, add 1/4 teasp. cinnamon.", recipe: magic_bars, user: danielle)
eleventh_review = Review.create!(body: "I used a combination of chocolate chips and butterscotch chips, and walnuts. I pre-mixed these along with the coconut, and poured the mixture over the condensed milk.", recipe: magic_bars, user: jenny)
twelvth_review = Review.create!(body: "These are fabulous. However, I increased the crust to 2 1/2 cups of crumbs and added a little more butter to the original recipe.", recipe: magic_bars, user: matt)
thirteenth_review = Review.create!(body: "I volunteered to bring something for our annual Christmas bazaar for church - even though I don't bake much any more. These were so easy to make!", recipe: magic_bars, user: susan)
